name: Deploy frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger frontend deploy
        run: |
          curl -X POST \
          -H "X-Commit-Sha: ${{ github.sha }}" \
          -H "X-Commit-Message: ${{ github.event.head_commit.message }}" \
          ${{ secrets.FRONTEND_WEBHOOK }}

